from . import start
from . import schedule
from . import first_connection
from . import trial_lesson
from . import about_us
from . import hall_location
from . import coaches
from . import price_list
from . import help
from . import menu
from . import text
